USE `contafc`;
UPDATE puc_cuentas SET nombre = 'ACTIVOS' WHERE codigo = '1' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'CIRCULANTE' WHERE codigo = '11' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Caja General' WHERE codigo = '11010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Caja Chica' WHERE codigo = '11010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Caja Especial Maparck' WHERE codigo = '11010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco X' WHERE codigo = '11020101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco X' WHERE codigo = '11020102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bco Occidente 11-701-001680-6' WHERE codigo = '11020103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bco Occidente 21-434-024809-5' WHERE codigo = '11020104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco X' WHERE codigo = '11020105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'BOFLOZA Occid 21-701-055679-3' WHERE codigo = '11020106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco Atlantida' WHERE codigo = '11020107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'BOFLOZA Occid 11-701-002172-9' WHERE codigo = '11020108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bco Atlantida 12-01-2020149-2' WHERE codigo = '11020109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuentas por cobrar Clientes' WHERE codigo = '11050101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Credito Fiscal SAR' WHERE codigo = '11050102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestamo por Cobrar Empleados' WHERE codigo = '11050120' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deudores Varios' WHERE codigo = '11050130' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Inca' WHERE codigo = '11050134' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Inventario' WHERE codigo = '11300101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Producto Terminado' WHERE codigo = '11300102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Inventario en Transito' WHERE codigo = '11300103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Inversiones' WHERE codigo = '11400104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Credito Fiscal Sersa' WHERE codigo = '11400105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Miguel Emilio Canahuati' WHERE codigo = '11400106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'FIJO' WHERE codigo = '12' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Maquinaria' WHERE codigo = '11500101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mobiliario y Equipo de Oficina' WHERE codigo = '11500102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sistema Contable' WHERE codigo = '11500103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vehiculos' WHERE codigo = '11500104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Equipo de Computo' WHERE codigo = '11500105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Terrenos' WHERE codigo = '11500108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Revaluacion de Activos' WHERE codigo = '11500109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'DIFERIDO' WHERE codigo = '13' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Organización' WHERE codigo = '11600101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depositos en Garantia' WHERE codigo = '11600102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Obras en Proceso' WHERE codigo = '11600103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Pagos a Cuenta ISR' WHERE codigo = '11600104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'DEI Credito Fiscal' WHERE codigo = '11600105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cta. Transitoria' WHERE codigo = '11600106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fondo de Pensiones' WHERE codigo = '11600125' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Activos' WHERE codigo = '11600126' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuentas por cobrar Socios' WHERE codigo = '11600127' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Activos' WHERE codigo = '11600128' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Reserva Laboral RAP' WHERE codigo = '11600129' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'FIJO' WHERE codigo = '12' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Maquinaria' WHERE codigo = '12010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mobiliario y Equipo de Oficina' WHERE codigo = '12010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sistema Contable' WHERE codigo = '12010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vehiculos' WHERE codigo = '12010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Equipo de Computo' WHERE codigo = '12010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Terrenos' WHERE codigo = '12010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Mant. De Calles' WHERE codigo = '12010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Alcantarillado' WHERE codigo = '12010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Electrificacion' WHERE codigo = '12010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'DIFERIDO' WHERE codigo = '13' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Obras en Proceso' WHERE codigo = '15010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Costos Agregados' WHERE codigo = '15010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PASIVO' WHERE codigo = '2' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'CIRCULANTE' WHERE codigo = '11' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuentas por Pagar Proveedores' WHERE codigo = '21010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sueldos y/o Remunerac. X Pagar' WHERE codigo = '21010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'XXXX' WHERE codigo = '21010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otras Cuentas C/Pagar' WHERE codigo = '21010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deca' WHERE codigo = '21010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Solar Trade Corporation' WHERE codigo = '21010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'INCA' WHERE codigo = '21010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'ECOENERGIA' WHERE codigo = '21010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones S/Vtasa por Pagar' WHERE codigo = '21010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Acreedores Varios' WHERE codigo = '21010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Anticipo de Clientes' WHERE codigo = '21010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sercon/Claro' WHERE codigo = '21010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuentas X Pagar/Miguel Canagua' WHERE codigo = '21010113' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Pasivos' WHERE codigo = '21010150' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PLANILLAS POR PAGAR' WHERE codigo = '22' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Reserva de Cuentas Incobrables' WHERE codigo = '22010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Aguinaldo' WHERE codigo = '22010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Catorceavo Mes' WHERE codigo = '22010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones' WHERE codigo = '22010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestaciones Laborales' WHERE codigo = '22010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Intereses de Empleados' WHERE codigo = '22010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Miguel Cinta' WHERE codigo = '22010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Miguel Emilio Canahuati' WHERE codigo = '22010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'ENEE' WHERE codigo = '22010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Seguro Contra Incendio' WHERE codigo = '22010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'OTRAS CUENTAS POR PAGAR' WHERE codigo = '23' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otras Cuentas por Pagar' WHERE codigo = '23010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'ISV Credito Fiscal' WHERE codigo = '23010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'ISV Credito Fiscal' WHERE codigo = '23010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Agencia Arevalo Fuentes' WHERE codigo = '23010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Agencia Aduanera Henry Zuniga' WHERE codigo = '23010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Solec Sorto' WHERE codigo = '23010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Hector Santiago Gutierrez' WHERE codigo = '23010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Emilio Elias Combustible' WHERE codigo = '23010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Misael Gomez' WHERE codigo = '23010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Transporte Hernandez' WHERE codigo = '23010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Autoexcel SA' WHERE codigo = '23010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Construcciones de Honduras' WHERE codigo = '23010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Transporte Bonilla Garcia' WHERE codigo = '23010115' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'DHL Honduras' WHERE codigo = '23010116' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Rapido Cargo' WHERE codigo = '23010117' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PRESTAMOS POR PAGAR' WHERE codigo = '24' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco Atlantida' WHERE codigo = '24010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestamos Empleados Atlantida' WHERE codigo = '24010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco de Occidednte' WHERE codigo = '24010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Banco Lafice' WHERE codigo = '24010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'RETENCIONES POR PAGAR' WHERE codigo = '25' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'IHSS' WHERE codigo = '25010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Rap Fosovi' WHERE codigo = '25010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Retencion de la Fuente ISR' WHERE codigo = '25010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Retencion 12.5 % ISR' WHERE codigo = '25010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuestro Vecinal por Pagar' WHERE codigo = '25010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Retencion del 1% ISR' WHERE codigo = '25010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Oftalmocentro' WHERE codigo = '25010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuesto Sobre Ventas Retenidas' WHERE codigo = '25010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuesto Volumen de Ventas' WHERE codigo = '25010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Optica Santa Lucia' WHERE codigo = '25010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Rest. Dist. Dividendos' WHERE codigo = '25010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'IMPUESTO SORELA RENTA' WHERE codigo = '26' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuesto Sobre la Renta' WHERE codigo = '26010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PASIVO FIJO' WHERE codigo = '27' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestamos L/Plazo' WHERE codigo = '27010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Ptmo. Banco Ocidente' WHERE codigo = '27010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'CUENTAS POR PAGAR A LARGO PLAZO' WHERE codigo = '28' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Terrenos - Distribucion Lotes' WHERE codigo = '28010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'inversiones Santa Fe' WHERE codigo = '28010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Eda Karina Parrales' WHERE codigo = '28010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PASIVO DIFERIDO' WHERE codigo = '29' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deprec. Acum. Maquinaria' WHERE codigo = '29010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deprec. Acum. Mobiliario y Equipo' WHERE codigo = '29010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deprec. Acum. Vehiculos' WHERE codigo = '29010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Deprec. Acum. Equipo de Computo' WHERE codigo = '29010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'PATRIMONIO Y CAPITAL' WHERE codigo = '3' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Capital Social' WHERE codigo = '31010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Reserva por Rev. De Activos' WHERE codigo = '31010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fondo de Reserva Legal 5%' WHERE codigo = '31010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Aportes Complementarios' WHERE codigo = '31010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Utilidad Acumulada' WHERE codigo = '31010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Utilidad del Periodo' WHERE codigo = '31010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'UTILIDAD O PERDIDA DE PERIODO' WHERE codigo = '36' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Utilidad del Periodo' WHERE codigo = '36050100' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Perdida del Periodo' WHERE codigo = '36100101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'INGRESOS' WHERE codigo = '4' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'VENTAS' WHERE codigo = '41' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Venta de Terrenos' WHERE codigo = '41010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Venta de Viviendas' WHERE codigo = '41010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cambios Condiciones Contratos' WHERE codigo = '41010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Productos Financieros' WHERE codigo = '41010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Limpieza Mantenimiento Lotes' WHERE codigo = '41010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Ingresos' WHERE codigo = '41010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'REBAJAS Y DESCUENTO' WHERE codigo = '42' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Rebajas/Descuentos S/V Vivienda' WHERE codigo = '42010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Rebajas/Descuentos S/V Terrenos' WHERE codigo = '42010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'GASTOS DE VENTA' WHERE codigo = '51' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sueldos y/o Remuneraciones' WHERE codigo = '51010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bonificaciones' WHERE codigo = '51010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Catorceavo Mes' WHERE codigo = '51010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vacaciones' WHERE codigo = '51010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Treceavo Mes' WHERE codigo = '51010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestaciones Laborales' WHERE codigo = '51010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Honorarios Profesionales' WHERE codigo = '51010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Atenciones y Agasajos' WHERE codigo = '51010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Viaje' WHERE codigo = '51010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Combustibles y Lubricantes' WHERE codigo = '51010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Publicidad, Propaganda y Susc.' WHERE codigo = '51010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Papeleria Y Utiles de Oficina' WHERE codigo = '51010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicios de Energia Electrica' WHERE codigo = '51010113' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicio de Agua Potable' WHERE codigo = '51010114' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicio Telefonia' WHERE codigo = '51010115' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicio Cable e Internet' WHERE codigo = '51010116' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento, Instalac. Sanita' WHERE codigo = '51010117' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Material Empaque/Embalaje' WHERE codigo = '51010118' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fletes y Encomiendas' WHERE codigo = '51010119' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento Calles y Avenidas' WHERE codigo = '51010120' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Reconocimiento Gastos Medicos' WHERE codigo = '51010121' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones (Tasa Seguridad)' WHERE codigo = '51010122' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Utensilios de Aseo y Limpieza' WHERE codigo = '51010123' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Insumos de Aseo' WHERE codigo = '51010124' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Matriculas y Multas' WHERE codigo = '51010125' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion-General' WHERE codigo = '51010126' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuestos Municipales, Otros' WHERE codigo = '51010127' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicios Legales' WHERE codigo = '51010128' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuesto Sobre La Renta' WHERE codigo = '51010129' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicios Bancarios (en Linea)' WHERE codigo = '51010130' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depreciacion Vehiculos' WHERE codigo = '51010131' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depreciacion Mobiliario y Equipo' WHERE codigo = '51010132' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'IHSS Patronal' WHERE codigo = '51010133' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimientos Instalaciones Fisicas' WHERE codigo = '51010134' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Donaciones/Regalias' WHERE codigo = '51010135' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Representacion' WHERE codigo = '51010136' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'RAP Fosovi Patronal' WHERE codigo = '51010137' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Renta Instalaciones Fisicas' WHERE codigo = '51010138' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenim. Mob. Equipo de Oficina' WHERE codigo = '51010139' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Construcciones, Manten. Calles' WHERE codigo = '51010140' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Permisos Municipales, Ambiente, Etc.' WHERE codigo = '51010141' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Sistema de Agua Potable' WHERE codigo = '51010142' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Soporte Sistema Informaticos' WHERE codigo = '51010143' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Sistema Aguas Negras' WHERE codigo = '51010144' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Urbanizacion Sistema Electrico' WHERE codigo = '51010145' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones S/Vta Terrenos/Casas' WHERE codigo = '51010146' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Renta Vehiculos' WHERE codigo = '51010147' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Miscelaneos' WHERE codigo = '51010148' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Regalias' WHERE codigo = '51010149' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'GASTOS ADMINISTRATIVOS' WHERE codigo = '53' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sueldos' WHERE codigo = '53010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bonificaciones' WHERE codigo = '53010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Aguinaldo' WHERE codigo = '53010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = '14avo Mes' WHERE codigo = '53010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vacaciones' WHERE codigo = '53010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = '13avo Mes' WHERE codigo = '53010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestaciones Laborales' WHERE codigo = '53010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Honorarios Profesionales' WHERE codigo = '53010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Atenciones y Agasajos' WHERE codigo = '53010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Viaje' WHERE codigo = '53010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Combustible y Lubricantes' WHERE codigo = '53010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Publicidad y Suscripciones' WHERE codigo = '53010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Papeleria y Utiles de Oficina' WHERE codigo = '53010113' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Servicios Publicos' WHERE codigo = '53010114' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depreciacion de Mobiliario' WHERE codigo = '53010115' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depreciacion de Vehiculos' WHERE codigo = '53010116' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Seguros' WHERE codigo = '53010117' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento de Vehiculos' WHERE codigo = '53010118' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Transporte' WHERE codigo = '53010119' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Alquileres' WHERE codigo = '53010120' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento Ofic. Mob. Y Equipo' WHERE codigo = '53010121' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Utencilios de Aseo' WHERE codigo = '53010122' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Amortizaciones' WHERE codigo = '53010123' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Impuestos Municipales, Otros' WHERE codigo = '53010124' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Capacitacion Personal' WHERE codigo = '53010125' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Seminarios Personal' WHERE codigo = '53010126' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bonificaciones' WHERE codigo = '53010127' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Entrenamiento y Capacitacion' WHERE codigo = '53010128' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vigilancia' WHERE codigo = '53010129' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones' WHERE codigo = '53010130' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Multas y Recargos' WHERE codigo = '53010131' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Remodelacion Local' WHERE codigo = '53010132' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Donaciones/Regalias' WHERE codigo = '53010134' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Internet' WHERE codigo = '53010135' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuerpo de Bomberos' WHERE codigo = '53010136' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos Medicos' WHERE codigo = '53010137' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Equipo de Computo' WHERE codigo = '53010138' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento Sistema Contabilidad' WHERE codigo = '53010139' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Camara de Comercio' WHERE codigo = '53010140' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Telefonia Celular' WHERE codigo = '53010141' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Derechos Laborales' WHERE codigo = '53010142' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Telefono Celular' WHERE codigo = '53010143' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Donativos/Contribuciones' WHERE codigo = '53010144' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Energia Electrica' WHERE codigo = '53010145' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Reparaciones' WHERE codigo = '53010146' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Honorarios Profesionales' WHERE codigo = '53010147' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Alquiler de Programa' WHERE codigo = '53010148' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Arreglos Florales' WHERE codigo = '53010149' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Colegio de Peritos' WHERE codigo = '53010150' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fotocopias y Encuadernados' WHERE codigo = '53010151' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Varios Miscelaneos' WHERE codigo = '53010152' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos Legales' WHERE codigo = '53010153' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Representacion' WHERE codigo = '53010154' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Matricula de Vehiculos' WHERE codigo = '53010155' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Exportacion' WHERE codigo = '53010156' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Encomiendas' WHERE codigo = '53010157' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'I.H.S.S. PATRONAL' WHERE codigo = '53010158' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Arrendamientos' WHERE codigo = '53010159' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Egresos Extraordinarios' WHERE codigo = '53010160' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Telefonia Celular' WHERE codigo = '53010161' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cargas y Descargas' WHERE codigo = '53010162' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Agua' WHERE codigo = '53010163' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos Licitacion' WHERE codigo = '53010164' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Muestras' WHERE codigo = '53010165' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos en Ferias' WHERE codigo = '53010166' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Timbres y Especies Fiscales' WHERE codigo = '53010167' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fletes y Encomiendas' WHERE codigo = '53010168' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bono Navideño' WHERE codigo = '53010169' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Accesorios Mitsubishi' WHERE codigo = '53010170' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Insumos Copiadora' WHERE codigo = '53010171' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fletes y Encomiendas' WHERE codigo = '53010172' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Dep. Mobiliario' WHERE codigo = '53010173' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comunicacion SKIPE' WHERE codigo = '53010174' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'CICH' WHERE codigo = '53010175' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'INFOP' WHERE codigo = '53010176' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'CHICO' WHERE codigo = '53010177' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'INFOP' WHERE codigo = '53010178' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento' WHERE codigo = '53010179' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Stickers-Publicitarios-Otros' WHERE codigo = '53010180' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cuota Patronal INFOP' WHERE codigo = '53010181' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de importacion' WHERE codigo = '53010182' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiednto de Edificios' WHERE codigo = '53010183' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Demora y Sobrestadia' WHERE codigo = '53010184' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Egresos Extraordinarios' WHERE codigo = '53010185' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Exportacion' WHERE codigo = '53010186' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Alimentacion' WHERE codigo = '53010187' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fumigacion y rodentizacion' WHERE codigo = '53010188' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Dominio Web Diconsa' WHERE codigo = '53010189' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Monitareo GPS' WHERE codigo = '53010190' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Depreciacion de vehiculos Empleados' WHERE codigo = '53010191' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Consultorias' WHERE codigo = '53010192' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Implementos al Personal' WHERE codigo = '53010193' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Viaticos' WHERE codigo = '53010194' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Insumos Copiadora' WHERE codigo = '53010195' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Auditorias Ambientales' WHERE codigo = '53010196' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Plan de Contigencias' WHERE codigo = '53010197' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Cable TV' WHERE codigo = '53010198' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'GASTOS FINANCIEROS' WHERE codigo = '54' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Intereses corrientes/Prestamo' WHERE codigo = '54010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Seguros S/Prestamos' WHERE codigo = '54010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos Bancarios' WHERE codigo = '54010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones Bancarias' WHERE codigo = '54010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comisiones por Hipotecas' WHERE codigo = '54010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Especies Fiscales' WHERE codigo = '54010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos por Garantia' WHERE codigo = '54010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Debitos Elab. Chequera' WHERE codigo = '54010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos de Avaluo' WHERE codigo = '54010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Diferencial Cambiario' WHERE codigo = '54010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Intereses Moratorios' WHERE codigo = '54010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comis. Liberacion Reservas' WHERE codigo = '54010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos Poliza de Seguros' WHERE codigo = '54010113' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos por CIC' WHERE codigo = '54010114' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Retencion Intereses' WHERE codigo = '54010115' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comision Tarjetas de Credito' WHERE codigo = '54010116' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Intereses Manejo de Linea de' WHERE codigo = '54010117' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Intereses Manejo de Linea de' WHERE codigo = '54010118' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Comision por Garantia Licitacion' WHERE codigo = '54010119' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Seguridad Poblacional' WHERE codigo = '54010120' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'GASTOS NO DEDUCIBLES' WHERE codigo = '55' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Infop' WHERE codigo = '55010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Multas y recargos' WHERE codigo = '55010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Gastos no Deducibles' WHERE codigo = '55010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'GASTOS DE ALMACEN' WHERE codigo = '56' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Sueldos y Salarios' WHERE codigo = '56010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Bonificaciones' WHERE codigo = '56010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Catorceavo Mes' WHERE codigo = '56010103' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Vacaciones' WHERE codigo = '56010104' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Treceavo Mes' WHERE codigo = '56010105' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Prestaciones Laborales' WHERE codigo = '56010106' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Atenciones y Agasajos' WHERE codigo = '56010107' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Combustibles y Lubricantes' WHERE codigo = '56010108' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Papeleria y Utiles de Oficina' WHERE codigo = '56010109' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento de Mob y Equipo' WHERE codigo = '56010110' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mantenimiento de Vehiculos' WHERE codigo = '56010111' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Fletes y Encomiendas' WHERE codigo = '56010112' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Egresos Extraordinarios' WHERE codigo = '56010113' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'COSTO DE VENTA' WHERE codigo = '6' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Costo de Ventas' WHERE codigo = '61010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'OTROS EGRESOS' WHERE codigo = '7' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Produccion en Proceso' WHERE codigo = '71010101' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Mano de Obra Directa' WHERE codigo = '71010102' AND empresa_id = 1;
UPDATE puc_cuentas SET nombre = 'Otros Gastos Otros Egresos' WHERE codigo = '71010103' AND empresa_id = 1;
